// * DEFAULT OBJECTS * \\

export const INITIAL_USERS = {
    loading: false,
    selected: null,
    users: null

};

// * ACTION TYPES * \\
export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';
export const REQUEST_GET_USERS_SUCCESS = 'REQUEST_GET_USERS_SUCCESS';
export const REQUEST_GET_USERS_FAIL = 'REQUEST_GET_USERS_FAIL';
export const REQUEST_GET_MORE_USERS = 'REQUEST_GET_MORE_USERS';
export const REQUEST_GET_MORE_USERS_SUCCESS = 'REQUEST_GET_MORE_USERS_SUCCESS';
export const REQUEST_GET_MORE_USERS_FAIL = 'REQUEST_GET_MORE_USERS_FAIL';
export const REQUEST_SELECT_USER = 'REQUEST_SELECT_USER';
export const DELETE_USER = 'DELETE_USER';

